---
title: "NY NOAA Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
data("ny_noaa")

ny_noaa_clean = ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  filter(snow >= 0 & !is.na(prcp) & !is.na(snow) & !is.na(snwd) & !is.na(tmax) & !is.na(tmin) & year > 1999) %>% 
  mutate(
    year = as.numeric(year),
    month = as.numeric(month),
    day = as.numeric(day),
    tmax = as.numeric(tmax) / 10,
    tmin = as.numeric(tmin) / 10,
    prcp = prcp / 10
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Snow Distribution by Monitoring Station 

```{r}
ny_noaa_clean %>% 
  filter(snow > 0 ) %>% 
  plot_ly(x = ~id, y = ~snow, color = ~id, type = "box", colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Daily Temperatures in 2005

```{r}
ny_noaa_clean %>%
  filter(year == 2005) %>% 
  mutate(text_label = str_c(month, "/", day, "/2005")) %>% 
  plot_ly(x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~month,
          text = ~text_label)
```

### Number of days with an observation above 90 degrees in the first decade of the 2000s...

```{r}
ny_noaa_clean %>% 
  filter(tmax > 32.2) %>% 
  distinct(year, month, day) %>% 
  group_by(year) %>% 
  mutate(n = n()) %>%
  distinct(year, n) %>% 
  plot_ly(x = ~year, y = ~n, color = ~year, type = "bar")
```

